version: "3"
services:
  influxdb:
    image: influxdb:${IMAGE_TAG_INFLUXDB}
    restart: ${RESTART_POLICY}
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_DATA_ENGINE
      - INFLUXDB_REPORTING_DISABLED
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      ## @TODO delete - /srv/docker/influxdb/data:/var/lib/influxdb
      - influxdb-storage:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      # for test purpose ONLY
      - ./server-cert.pem:/etc/ssl/influxdb/server-cert.pem:ro
      - ./server-key.pem:/etc/ssl/influxdb/server-key.pem:ro
    networks:
      influxdb:

  telegraf:
    image: telegraf:${IMAGE_TAG_TELEGRAF}
    network_mode: host
    # https://docs.docker.com/compose/compose-file/
    cap_add:
      - NET_ADMIN
    restart: ${RESTART_POLICY}
    container_name: telegraf
    environment:
      - HOST_ETC
      - HOST_PROC
      - HOST_SYS
      - HOST_VAR
      - HOST_RUN
      - HOST_MOUNT_PREFIX
      # set here the real influx host
      - INFLUXDB_URI
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # from here
      # https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md 
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
  
  grafana:
    image: grafana/grafana:${IMAGE_TAG_GRAFANA}
    restart: ${RESTART_POLICY}
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    volumes:
      # Data persistency
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      # from here: https://github.com/aerokube/selenoid-grafana-example/blob/master/docker-compose.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # @TODO not for end version
      GF_SERVER_ROUTER_LOGGING: "true"
      GF_LOG_LEVEL: "debug"
      GF_LOG_MODE: "console"
    networks:
      influxdb:

networks:
  influxdb:


volumes:
  influxdb-storage:
  grafana-storage:
