version: "3"
services:
  influxdb:
    image: influxdb:${IMAGE_TAG_INFLUXDB}
    restart: ${RESTART_POLICY}
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      influxdb:

  telegraf:
    image: telegraf:${IMAGE_TAG_TELEGRAF}
    restart: ${RESTART_POLICY}
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      influxdb:

  grafana:
    image: grafana/grafana:${IMAGE_TAG_GRAFANA}
    restart: ${RESTART_POLICY}
    container_name: grafana
    ports:
      - "3000:3000"
    ##env_file:
    ##  - "env.grafana"
    user: "0"
    #links:
    #  - influxdb
    depends_on:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      ## - /srv/docker/grafana/data:/var/lib/grafana
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning

networks:
  influxdb:

volumes:
  influxdb-storage:
  grafana-storage:
